# -*- coding: utf-8 -*-
__author__ = 'xiliangma'

SYSTEM_ERROR = 1

USER_IS_REGISTERED_ERROR = 20
USER_NOT_EXIST_ERROR = 21
USER_PWD_ERROR = 22

RANDOM_CODE_VALIDATE_ERROR = 40
RANDOM_CODE_INVALID_ERROR = 41
RANDOM_NOT_EXIST_ERROR = 42

